package com.deepak.mobikwikimage.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.deepak.mobikwikimage.database.PhotoUnsplash;

import com.deepak.mobikwikimage.database.PhotoUnsplashDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoUnsplashDaoConfig;

    private final PhotoUnsplashDao photoUnsplashDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoUnsplashDaoConfig = daoConfigMap.get(PhotoUnsplashDao.class).clone();
        photoUnsplashDaoConfig.initIdentityScope(type);

        photoUnsplashDao = new PhotoUnsplashDao(photoUnsplashDaoConfig, this);

        registerDao(PhotoUnsplash.class, photoUnsplashDao);
    }
    
    public void clear() {
        photoUnsplashDaoConfig.clearIdentityScope();
    }

    public PhotoUnsplashDao getPhotoUnsplashDao() {
        return photoUnsplashDao;
    }

}
