package com.deepak.mobikwikimage.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PHOTO_UNSPLASH".
 */
@Entity
public class PhotoUnsplash {

    @Id
    private String id;
    private String alt_description;
    private byte[] imageData;
    private String urls;

    @Index
    private Integer page;

    @Generated
    public PhotoUnsplash() {
    }

    public PhotoUnsplash(String id) {
        this.id = id;
    }

    @Generated
    public PhotoUnsplash(String id, String alt_description, byte[] imageData, String urls, Integer page) {
        this.id = id;
        this.alt_description = alt_description;
        this.imageData = imageData;
        this.urls = urls;
        this.page = page;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAlt_description() {
        return alt_description;
    }

    public void setAlt_description(String alt_description) {
        this.alt_description = alt_description;
    }

    public byte[] getImageData() {
        return imageData;
    }

    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }

    public String getUrls() {
        return urls;
    }

    public void setUrls(String urls) {
        this.urls = urls;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

}
